// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.9.0
// source: api/landscape/v1/exhibition.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExhibitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateExhibitionRequest) Reset() {
	*x = CreateExhibitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExhibitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExhibitionRequest) ProtoMessage() {}

func (x *CreateExhibitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExhibitionRequest.ProtoReflect.Descriptor instead.
func (*CreateExhibitionRequest) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{0}
}

type CreateExhibitionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateExhibitionReply) Reset() {
	*x = CreateExhibitionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExhibitionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExhibitionReply) ProtoMessage() {}

func (x *CreateExhibitionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExhibitionReply.ProtoReflect.Descriptor instead.
func (*CreateExhibitionReply) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{1}
}

type UpdateExhibitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateExhibitionRequest) Reset() {
	*x = UpdateExhibitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExhibitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExhibitionRequest) ProtoMessage() {}

func (x *UpdateExhibitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExhibitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateExhibitionRequest) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{2}
}

type UpdateExhibitionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateExhibitionReply) Reset() {
	*x = UpdateExhibitionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateExhibitionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExhibitionReply) ProtoMessage() {}

func (x *UpdateExhibitionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExhibitionReply.ProtoReflect.Descriptor instead.
func (*UpdateExhibitionReply) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{3}
}

type DeleteExhibitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteExhibitionRequest) Reset() {
	*x = DeleteExhibitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExhibitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExhibitionRequest) ProtoMessage() {}

func (x *DeleteExhibitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExhibitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteExhibitionRequest) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{4}
}

type DeleteExhibitionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteExhibitionReply) Reset() {
	*x = DeleteExhibitionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteExhibitionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExhibitionReply) ProtoMessage() {}

func (x *DeleteExhibitionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExhibitionReply.ProtoReflect.Descriptor instead.
func (*DeleteExhibitionReply) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{5}
}

type GetExhibitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetExhibitionRequest) Reset() {
	*x = GetExhibitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExhibitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExhibitionRequest) ProtoMessage() {}

func (x *GetExhibitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExhibitionRequest.ProtoReflect.Descriptor instead.
func (*GetExhibitionRequest) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{6}
}

type GetExhibitionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetExhibitionReply) Reset() {
	*x = GetExhibitionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExhibitionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExhibitionReply) ProtoMessage() {}

func (x *GetExhibitionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExhibitionReply.ProtoReflect.Descriptor instead.
func (*GetExhibitionReply) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{7}
}

type ListExhibitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListExhibitionRequest) Reset() {
	*x = ListExhibitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExhibitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExhibitionRequest) ProtoMessage() {}

func (x *ListExhibitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExhibitionRequest.ProtoReflect.Descriptor instead.
func (*ListExhibitionRequest) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{8}
}

type ListExhibitionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListExhibitionReply) Reset() {
	*x = ListExhibitionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_landscape_v1_exhibition_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListExhibitionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExhibitionReply) ProtoMessage() {}

func (x *ListExhibitionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_landscape_v1_exhibition_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExhibitionReply.ProtoReflect.Descriptor instead.
func (*ListExhibitionReply) Descriptor() ([]byte, []int) {
	return file_api_landscape_v1_exhibition_proto_rawDescGZIP(), []int{9}
}

var File_api_landscape_v1_exhibition_proto protoreflect.FileDescriptor

var file_api_landscape_v1_exhibition_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x65, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61,
	0x70, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45,
	0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x17, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x78,
	0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a,
	0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x17, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32,
	0x85, 0x04, 0x0a, 0x0a, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x66,
	0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61,
	0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69,
	0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x66, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61, 0x6e, 0x64,
	0x73, 0x63, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x66,
	0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61,
	0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69,
	0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x45, 0x78, 0x68,
	0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61,
	0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78,
	0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x60, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x68,
	0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61,
	0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x78, 0x68, 0x69, 0x62, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x34, 0x0a, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x6c,
	0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1e, 0x71,
	0x75, 0x69, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x61,
	0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_landscape_v1_exhibition_proto_rawDescOnce sync.Once
	file_api_landscape_v1_exhibition_proto_rawDescData = file_api_landscape_v1_exhibition_proto_rawDesc
)

func file_api_landscape_v1_exhibition_proto_rawDescGZIP() []byte {
	file_api_landscape_v1_exhibition_proto_rawDescOnce.Do(func() {
		file_api_landscape_v1_exhibition_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_landscape_v1_exhibition_proto_rawDescData)
	})
	return file_api_landscape_v1_exhibition_proto_rawDescData
}

var file_api_landscape_v1_exhibition_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_landscape_v1_exhibition_proto_goTypes = []interface{}{
	(*CreateExhibitionRequest)(nil), // 0: api.landscape.v1.CreateExhibitionRequest
	(*CreateExhibitionReply)(nil),   // 1: api.landscape.v1.CreateExhibitionReply
	(*UpdateExhibitionRequest)(nil), // 2: api.landscape.v1.UpdateExhibitionRequest
	(*UpdateExhibitionReply)(nil),   // 3: api.landscape.v1.UpdateExhibitionReply
	(*DeleteExhibitionRequest)(nil), // 4: api.landscape.v1.DeleteExhibitionRequest
	(*DeleteExhibitionReply)(nil),   // 5: api.landscape.v1.DeleteExhibitionReply
	(*GetExhibitionRequest)(nil),    // 6: api.landscape.v1.GetExhibitionRequest
	(*GetExhibitionReply)(nil),      // 7: api.landscape.v1.GetExhibitionReply
	(*ListExhibitionRequest)(nil),   // 8: api.landscape.v1.ListExhibitionRequest
	(*ListExhibitionReply)(nil),     // 9: api.landscape.v1.ListExhibitionReply
}
var file_api_landscape_v1_exhibition_proto_depIdxs = []int32{
	0, // 0: api.landscape.v1.Exhibition.CreateExhibition:input_type -> api.landscape.v1.CreateExhibitionRequest
	2, // 1: api.landscape.v1.Exhibition.UpdateExhibition:input_type -> api.landscape.v1.UpdateExhibitionRequest
	4, // 2: api.landscape.v1.Exhibition.DeleteExhibition:input_type -> api.landscape.v1.DeleteExhibitionRequest
	6, // 3: api.landscape.v1.Exhibition.GetExhibition:input_type -> api.landscape.v1.GetExhibitionRequest
	8, // 4: api.landscape.v1.Exhibition.ListExhibition:input_type -> api.landscape.v1.ListExhibitionRequest
	1, // 5: api.landscape.v1.Exhibition.CreateExhibition:output_type -> api.landscape.v1.CreateExhibitionReply
	3, // 6: api.landscape.v1.Exhibition.UpdateExhibition:output_type -> api.landscape.v1.UpdateExhibitionReply
	5, // 7: api.landscape.v1.Exhibition.DeleteExhibition:output_type -> api.landscape.v1.DeleteExhibitionReply
	7, // 8: api.landscape.v1.Exhibition.GetExhibition:output_type -> api.landscape.v1.GetExhibitionReply
	9, // 9: api.landscape.v1.Exhibition.ListExhibition:output_type -> api.landscape.v1.ListExhibitionReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_landscape_v1_exhibition_proto_init() }
func file_api_landscape_v1_exhibition_proto_init() {
	if File_api_landscape_v1_exhibition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_landscape_v1_exhibition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExhibitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_landscape_v1_exhibition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExhibitionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_landscape_v1_exhibition_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExhibitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_landscape_v1_exhibition_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateExhibitionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_landscape_v1_exhibition_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExhibitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_landscape_v1_exhibition_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteExhibitionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_landscape_v1_exhibition_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExhibitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_landscape_v1_exhibition_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExhibitionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_landscape_v1_exhibition_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExhibitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_landscape_v1_exhibition_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListExhibitionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_landscape_v1_exhibition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_landscape_v1_exhibition_proto_goTypes,
		DependencyIndexes: file_api_landscape_v1_exhibition_proto_depIdxs,
		MessageInfos:      file_api_landscape_v1_exhibition_proto_msgTypes,
	}.Build()
	File_api_landscape_v1_exhibition_proto = out.File
	file_api_landscape_v1_exhibition_proto_rawDesc = nil
	file_api_landscape_v1_exhibition_proto_goTypes = nil
	file_api_landscape_v1_exhibition_proto_depIdxs = nil
}
