// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"landscape/internal/biz"
	"landscape/internal/conf"
	"landscape/internal/data"
	"landscape/internal/server"
	"landscape/internal/service"

	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	landscapeRepo := data.NewEssayRepo(dataData, logger)
	landscapeUsecase := biz.NewLandscapeUsecase(landscapeRepo, logger)
	landscapeService := service.NewLandscapeServiceService(landscapeUsecase)
	grpcServer := server.NewGRPCServer(confServer, landscapeService, logger)
	httpServer := server.NewHTTPServer(confServer, landscapeService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
